# Application name
spring.application.name=activity-service

# Server port
server.port=8082

# MongoDB configuration
spring.data.mongodb.uri=mongodb://localhost:27017/fitness-activity
spring.data.mongodb.database=fitness-activity

# Eureka client configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Force Eureka to use the actual server port instead of default 8080
eureka.instance.non-secure-port=${server.port}
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
