# Server port
server.port=8082

# MongoDB configuration
spring.data.mongodb.uri=mongodb://localhost:27017/fitness-activity
spring.data.mongodb.database=fitness-activity

# Eureka client configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# rabbitmq configuration
rabbitmq.exchange.name=fitness.exchange
rabbitmq.queue.name=activity.queue
rabbitmq.routing.key=activity.tracking

rabbitmq.server=localhost
rabbitmq.port=5672
rabbitmq.username=guest
rabbitmq.password=guest
