eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

server.port=8083
#MongoDB configuration
spring.data.mongodb.uri=mongodb://localhost:27017/fitness-recommendation
spring.data.mongodb.database=fitness-recommendation
# rabbitmq configuration
rabbitmq.exchange.name=fitness.exchange
rabbitmq.queue.name=activity.queue
rabbitmq.routing.key=activity.tracking

rabbitmq.server=localhost
rabbitmq.port=5672
rabbitmq.username=guest
rabbitmq.password=guest

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
gemini.api.key={GEMINI_API_KEY}